name: make
on: workflow_dispatch
permissions:
  pages: write
  id-token: write
jobs:
  make:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - run: brew install libffi gettext glib pkg-config pixman ninja meson
      - run: ./configure --static
      - run: make
      - run: mkdir _site/
      - run: echo '<a href="qemu-macos.tar.gz">DOWNLOAD</a>' > _site/index.html
      - run: tar czvf _site/qemu-macos.tar.gz build/
      - uses: actions/upload-pages-artifact@v3
      - uses: actions/deploy-pages@v4
